- hosts: all
  remote_user: ec2-user
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: Test echo command
      debug:
        msg: "My username is {{ admin_username }} and password is {{ admin_password }}"
