- hosts: all
  remote_user: ec2-user
  become: yes
  vars_files:
    - myconfig.yml
  tasks:
    - name: Test echo command
      debug:
        msg: "My username is {{ username }} and password is {{ password }}"